### ISSUE TITLE
Support `defineEmits`

### ISSUE THREAD

**Issue by so1ve** [unplugin/unplugin-vue-complex-types#25]
### Additional context

https://github.com/vuejs/core/issues/9541

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JounQin** [comment]
```log
[plugin:unplugin-vue-complex-types] ts.isIntersectionTypeNode is not a function
/Users/JounQin/Workspaces/Outsouring/coin/frontend/src/components/TokenSearchModal.vue
    at Printer.print (file:///Users/JounQin/Workspaces/Outsouring/coin/frontend/node_modules/unplugin-vue-complex-types/dist/index.mjs:220:12)
    at transform (file:///Users/JounQin/Workspaces/Outsouring/coin/frontend/node_modules/unplugin-vue-complex-types/dist/index.mjs:250:31)
    at TransformContext.transform (file:///Users/JounQin/Workspaces/Outsouring/coin/frontend/node_modules/unplugin-vue-complex-types/dist/index.mjs:267:12)
    at Object.transform (file:///Users/JounQin/Workspaces/Outsouring/coin/frontend/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:44345:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadAndTransform (file:///Users/JounQin/Workspaces/Outsouring/coin/frontend/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:55015:29)
    at async viteTransformMiddleware (file:///Users/JounQin/Workspaces/Outsouring/coin/frontend/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:64417:32
```

```json
{
  "typescript": "^5.2.2"
}
```

```ts
const emit = defineEmits<{
  activePairChange: [pair: Pair]
  'update:open': [open: boolean]
}>()
```

**Comment by so1ve** [comment]
@JounQin This looks pretty weird, currently we doesn't process `defineEmits` at all. Could you please open a new issue with minimal reproduction? Thanks!

**Comment by so1ve** [comment]
@JounQin Just curious: since `defineEmits`'s event argument type doesn't affect runtime, what about we transform it to
```ts
defineEmits(['activePairChange', 'update:open'])
```
?

**Comment by JounQin** [comment]
Thanks for confirming, I think that would work as expected.
