### ISSUE TITLE
ts.isIntersectionTypeNode is not a function

### ISSUE THREAD

**Issue by shilim-developer** [unplugin/unplugin-vue-complex-types#27]
### Describe the bug

13:36:08 [vite] Internal server error: ts.isIntersectionTypeNode is not a function
  Plugin: unplugin-vue-complex-types
  File: E:/git/vue3-modal-demo/src/components/CommandDialog.vue
      at Printer.print (file:///E:/git/vue3-modal-demo/node_modules/unplugin-vue-complex-types/dist/index.mjs:224:12)
      at transform (file:///E:/git/vue3-modal-demo/node_modules/unplugin-vue-complex-types/dist/index.mjs:254:31)
      at TransformContext.transform (file:///E:/git/vue3-modal-demo/node_modules/unplugin-vue-complex-types/dist/index.mjs:272:12)      
      at Object.transform (file:///E:/git/vue3-modal-demo/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44352:62)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async loadAndTransform (file:///E:/git/vue3-modal-demo/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55026:29)
      at async viteTransformMiddleware (file:///E:/git/vue3-modal-demo/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:64430:32) 

### Reproduction

only import

### System Info

```Shell
System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 5.49 GB / 15.85 GB
  Binaries:
    Node: 16.14.0 
    Yarn: 1.22.19 
    npm: 9.7.1 
    pnpm: 8.6.1
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.19041.1202
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by so1ve** [comment]
My bad. Released `v0.2.1`
